version: '3.1'

services:
  db:
    container_name: ideas_combine_postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ideas_combine
volumes:
  postgres_data:
