version: '3.1'

services:
  app:
    container_name: ideas_combine_app
    networks:
      - items_combine_network
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: ideas_combine_postgres
    image: postgres
    networks:
      - items_combine_network
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ideas_combine

volumes:
  postgres_data:

networks:
  items_combine_network:
