version: '3.1'

services:
  db:
    container_name: ideas_combine_postgres_dev
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${POSTGRES_TZ}

volumes:
  postgres_data_dev:
