databases:
  - name: POSTGRES_DB
    databaseName: POSTGRES_DB
    user: POSTGRES_USER

 services:
 - type: web
   name: POSTGRES_DB
   runtime: docker
   plan: free
   envVars:
   - key: DATABASE_URL
     fromDatabase:
       name: POSTGRES_DB
       property: connectionString